[libraries]
defaultlib.files = [
    './src/a7_lite_board.vhd',
    './src/ax309_board.vhd',
    './src/zedboard.vhd',
    './src/common/clk_gen/clk_gen_z7.vhd',
    './src/common/pulse_gen/pulse_gen.vhd',
    './src/common/pkg/util_pkg.vhd',
    './src/hello_world/hello_world.vhd'
]

unisim.files = [
    "/opt/Xilinx/Vivado/2024.2/data/vhdl/src/unisims/unisim_VCOMP.vhd"
]
unisim.is_third_party = true